name: workflow for Master
on:
  workflow_dispatch:
  push:
    branches:
      - "main" #only on master
      - staging
      - trying
jobs:
  build:
    runs-on: ubuntu-latest
    # outputs:
    #   image_name: ${{ steps.build.outputs.image_name }}
    #   image_tag: ${{ steps.build.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v3
      # - uses: ./.github/test
      #   id: build
      #   with:
      #     test: "eu"
      - name: releae
        id: release-date
        run: |
          echo "::set-output name=release_date::20220720"

  ci-success:
    name: ci
    if: ${{ success() }}
    needs:
      # - exfm
      - build
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0

